[
  {":0:unknown_function Function Stored\.Item\.Atom\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.BitString\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Float\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Function\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Integer\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.List\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Map\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.PID\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Port\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Reference\.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Stored\.Item\.Tuple\.__impl__/1 does not exist.",
   :unknown_function}
]
