name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [21.x, 22.x]
        elixir: [1.7.x, 1.8.x, 1.9.x, 1.10.x]

    steps:
      - uses: actions/checkout@v1.0.0

      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v1
        with:
          path: _build/dev
          key: dialyzer-plt-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            dialyzer-plt-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
            dialyzer-plt-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Test
        run: mix test

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status

  test-otp-23:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [23.x]
        elixir: [1.9.x, 1.10.x]

    steps:
      - uses: actions/checkout@v1.0.0

      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v1
        with:
          path: _build/dev
          key: dialyzer-plt-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            dialyzer-plt-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
            dialyzer-plt-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Test
        run: mix test

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
